name: E2E on Chrome
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
      runs-on: ubuntu-latest
      steps:
        # Checkout the Repo
        - uses: actions/checkout@v2

        # Install Node 12
        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: 12

        # Install dependencies
        - run: npm install

        # Run tests
        - run: npm run unit
  cypress-run:
    runs-on: ubuntu-20.04
    # let's make sure our tests pass on Chrome browser
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
